# Generated by Django 5.1.3 on 2025-01-16 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(default='SQL', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('summary', models.BooleanField(default=False)),
                ('isSoil', models.BooleanField(default=False)),
                ('isTime', models.BooleanField(default=False)),
                ('canSpline', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('county', models.CharField(default='', max_length=255)),
                ('county_id', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=255)),
                ('state_id', models.CharField(default='', max_length=255)),
                ('source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.source')),
            ],
            options={
                'order_with_respect_to': 'name',
                'unique_together': {('name', 'source')},
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('hasSoil', models.BooleanField(default=False)),
                ('hasTime', models.BooleanField(default=False)),
                ('file', models.URLField(max_length=255)),
                ('delimiter', models.CharField(default=',', max_length=1)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.source')),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('dataset', models.ManyToManyField(to='base.dataset')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.standard')),
            ],
        ),
        migrations.CreateModel(
            name='Pedon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('x', models.TextField(default='')),
                ('splineCoeffs', models.TextField(default='')),
                ('BDc', models.TextField(default='')),
                ('SOCc', models.TextField(default='')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.site')),
            ],
            options={
                'order_with_respect_to': 'name',
                'unique_together': {('name', 'site')},
            },
        ),
    ]
