# Generated by Django 5.1.3 on 2025-01-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonym',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterOrderWithRespectTo(
            name='synonym',
            order_with_respect_to='name',
        ),
        migrations.AlterUniqueTogether(
            name='synonym',
            unique_together={('name', 'standard')},
        ),
    ]
