# Generated by Django 5.1.3 on 2025-03-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_standard_naltid_alter_dataset_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedon',
            name='BDc',
        ),
        migrations.RemoveField(
            model_name='pedon',
            name='SOCc',
        ),
        migrations.AlterField(
            model_name='pedon',
            name='splineCoeffs',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pedon',
            name='x',
            field=models.JSONField(default=list),
        ),
    ]
